// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoMkF3_uc3378_aLH9lNGXB7zIC2jCrEc',
    appId: '1:80980093500:web:a5b152fe1dc3ec5692f139',
    messagingSenderId: '80980093500',
    projectId: 'crud2406c2',
    authDomain: 'crud2406c2.firebaseapp.com',
    storageBucket: 'crud2406c2.firebasestorage.app',
    measurementId: 'G-MY0PVV5T30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHSw19kOUCFgB_1wwbeaZBVTEktgtsGyI',
    appId: '1:80980093500:android:e71d5fa858bfbbb492f139',
    messagingSenderId: '80980093500',
    projectId: 'crud2406c2',
    storageBucket: 'crud2406c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Ocdr_z1CLom4yrHxcQJCFnUQpNLnEYQ',
    appId: '1:80980093500:ios:c384da2a415ebb8e92f139',
    messagingSenderId: '80980093500',
    projectId: 'crud2406c2',
    storageBucket: 'crud2406c2.firebasestorage.app',
    iosBundleId: 'com.example.myflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Ocdr_z1CLom4yrHxcQJCFnUQpNLnEYQ',
    appId: '1:80980093500:ios:c384da2a415ebb8e92f139',
    messagingSenderId: '80980093500',
    projectId: 'crud2406c2',
    storageBucket: 'crud2406c2.firebasestorage.app',
    iosBundleId: 'com.example.myflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoMkF3_uc3378_aLH9lNGXB7zIC2jCrEc',
    appId: '1:80980093500:web:6b374dc6785e64a392f139',
    messagingSenderId: '80980093500',
    projectId: 'crud2406c2',
    authDomain: 'crud2406c2.firebaseapp.com',
    storageBucket: 'crud2406c2.firebasestorage.app',
    measurementId: 'G-NNDGKSHSG5',
  );
}
